name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - gnuplot
  - gradio=3.50.2
  - gunicorn=20.1.0
  - joblib=1.3.2
  - omnixai=1.3.1
  - numpy=1.23.5
  - scikit-learn=1.1.3
  - xgboost